root: true

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

extends:
  - "plugin:@typescript-eslint/recommended"
  - dipasqualew/mixins/base
  - dipasqualew/mixins/imports
  - dipasqualew/mixins/ts

env:
  es6: true
  node: true

rules:
  camelcase: 'off'
