root: true

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

extends:
  - "plugin:@typescript-eslint/recommended"

env:
  es6: true
  node: true

rules:
  indent:
    - error
    - 2

  semi:
    - error
    - always

  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
